### ISSUE TITLE
Sagger

### ISSUE THREAD

**Issue by Snakybo** [DutchBeastman/MissleCommand-#1]
ik had altijd al je code uit de 2e willen stelen

**Comment by DutchBeastman** [comment]
ik dacht heb je wel nodig bij sticky

**Comment by DutchBeastman** [comment]
dit kan dus
okay

**Comment by Snakybo** [comment]
focku

**Comment by DutchBeastman** [comment]
filthymonaky

**Comment by DutchBeastman** [comment]
dit was closed 
stop met erop reageren

**Comment by Snakybo** [comment]
doe eens niet zo rasisties

**Comment by DutchBeastman** [comment]
pls dangerdolan

**Comment by DutchBeastman** [comment]
ga eens je dingen doen ipv hier op reagerebn

**Comment by Snakybo** [comment]
soenpai pls
